"""Sign-off documents, Quinn's test plan → approval → test sign-off report, the Testing API, the user's policy changes
(Orion's rules), and the demo-run guard. No AWS, no AI calls."""
import asyncio
import json

import pytest
from fastapi.testclient import TestClient

from app.agents import qa
from app.main import app
from app.orchestrator import flow
from app.orchestrator import runner as runner_mod
from app.services import aws_access, signoff
from app.services import tickets as tk
from app.services.storage import ProjectStore
from tests.conftest import signup

PLAN = {"summary": "Covers the order flow.", "scope": "API → Lambda → SQS", "approach": "live, from outside",
        "out_of_scope": [{"what": "SQS outage", "why": "can't be simulated without breaking the infrastructure"}],
        "entry_criteria": ["code deployed"], "exit_criteria": ["all high-priority scenarios pass"], "changes": "",
        "cases": [{"id": "TC-01", "title": "Valid order lands in the queue", "category": "happy path", "priority": "high", "requirement_ref": "§3",
                   "preconditions": "", "steps": "POST /orders", "test_data": "happy_path", "expected": "200 and the JSON in orders.fifo"},
                  {"id": "TC-02", "title": "Missing OrderId is rejected", "category": "negative", "priority": "high", "requirement_ref": "§4",
                   "preconditions": "", "steps": "POST /orders", "test_data": "missing_order_id", "expected": "400, nothing queued"}]}


@pytest.fixture
def captured(monkeypatch):
    jobs: list[tuple[str, dict]] = []

    async def enqueue(kind, project_id=None, **payload):
        jobs.append((kind, payload))
        return "job_x"
    monkeypatch.setattr(runner_mod.runner, "enqueue", enqueue)
    return jobs


def _project(name: str) -> tuple[TestClient, str]:
    c = TestClient(app)
    signup(c, name)
    return c, c.post("/api/projects", json={"name": name.title()}).json()["id"]


def test_every_approval_writes_the_agents_signoff(client, captured):
    c, pid = _project("signer")

    async def go():
        a = await flow.request_approval(pid, "mapping", "Atlas's data mapping", "5 rows, 14 examples", ["01_data_mapping.md"])
        await flow.decide(pid, a.id, "changes", "Add the currency rule")
        b = await flow.request_approval(pid, "mapping", "Atlas's data mapping (revised)", "6 rows, 14 examples", ["01_data_mapping.md"])
        await flow.decide(pid, b.id, "approve", "Looks right")
    asyncio.run(go())
    doc = ProjectStore(pid).read(signoff.path("mapping")).decode()
    assert "# Sign-off · Data mapping" in doc and "Atlas (Data Analyst)" in doc
    assert "changes requested: Atlas's data mapping. “Add the currency rule”" in doc and "✅ approved: Atlas's data mapping (revised). “Looks right”" in doc
    assert "`01_data_mapping.md`" in doc and "Nothing in it is generated by AI" in doc
    lst = c.get(f"/api/projects/{pid}/signoffs").json()
    assert {"stage": "mapping", "order": "02", "agent": "ba", "title": "Data mapping", "path": "signoff/02-mapping.md"} in lst


def test_test_plan_needs_the_leads_approval_and_goes_stale_with_the_requirement(client, captured):
    c, pid = _project("planner")
    store = ProjectStore(pid)
    store.write("00_requirement.md", "# Requirement v1")
    p = {**PLAN, "version": "v1.0", "basis": qa.plan_basis(pid), "status": "proposed"}
    store.write(qa.PLAN_JSON, json.dumps(p))
    assert not qa.plan_ready(pid)  # proposed: Quinn may not test yet

    async def go():
        a = await flow.request_approval(pid, "test_plan", "Quinn's test plan: 2 scenarios", "…", [qa.PLAN_MD])
        await flow.decide(pid, a.id, "approve", "")
    asyncio.run(go())
    assert qa.plan_ready(pid) and captured[-1][0] == "qa.live"  # approved → Quinn runs it
    md = store.read(qa.PLAN_MD).decode()
    assert "✅ Approved by the test lead" in md and "| TC-02 | Missing OrderId is rejected | negative | high |" in md
    assert "**SQS outage**: can't be simulated" in md
    assert "signoff/09-test-plan.md" in {f["path"] for f in store.tree()}
    store.write("00_requirement.md", "# Requirement v1.1: a new field")
    assert not qa.plan_ready(pid)  # the requirement changed: the plan is redone before the next run


def test_the_test_signoff_report_has_results_tickets_and_who_fixed_them(client, captured):
    c, pid = _project("reporter")
    store = ProjectStore(pid)
    store.write(qa.PLAN_JSON, json.dumps({**PLAN, "version": "v1.2", "basis": qa.plan_basis(pid), "status": "approved", "approved_at": "2026-10-02 14:00 UTC"}))

    async def go():
        t = await tk.create(pid, title="Missing OrderId accepted", area="code", reporter="qa", check_id="TC-02", version="v1.2", announce=False)
        await tk.change(t.id, "de", "Fixed with a regression test", status="resolved", assignee="qa", version_fixed="v1.3", say=False)
        await tk.change(t.id, "qa", "Retested: fixed", status="closed", say=False)
    asyncio.run(go())
    store.write(qa.LIVE_JSON, json.dumps({"summary": "All good.", "version": "v1.3", "deployed_version": "v1.3", "calls": 9, "role": "orkestra-x-quinn",
                                          "checks": [{"id": "TC-01", "title": "Valid order", "passed": True, "evidence": "200, JSON in the queue"},
                                                     {"id": "TC-02", "title": "Missing OrderId", "passed": True, "evidence": "400 rejected"}],
                                          "not_run": [], "risks": ["SQS outage only covered by unit tests"], "signoff": "Fit to go live."}))
    qa._save_run(pid, {"at": "2026-10-02 14:10 UTC", "version": "v1.2", "kind": "full", "passed": 1, "failed": 1, "not_run": 0,
                       "created": ["TKT-001"], "closed": [], "reopened": [], "checks": [], "calls": 8})
    qa._save_run(pid, {"at": "2026-10-02 14:40 UTC", "version": "v1.3", "kind": "retest", "passed": 2, "failed": 0, "not_run": 0,
                       "created": [], "closed": ["TKT-001"], "reopened": [], "checks": [], "calls": 9})
    p = asyncio.run(signoff.write_test_signoff(pid))
    doc = store.read(p).decode()
    assert "✅ **Signed off by Quinn**, waiting for" in doc and "> **Quinn:** Fit to go live." in doc
    assert "| TC-02 | Missing OrderId is rejected | negative | high | ✅ pass | 400 rejected |" in doc
    assert "| TKT-001 | Missing OrderId accepted | major | code | Quinn | Dev | v1.2 | v1.3 | closed |" in doc  # raised by Quinn, fixed by Dev
    assert "| 2 | 2026-10-02 14:40 UTC | v1.3 | retest | 2 | 0 |" in doc and "SQS outage only covered by unit tests" in doc
    assert "✅ Every planned scenario executed" in doc and "approved by" in doc
    t = c.get(f"/api/projects/{pid}/testing").json()
    assert t["plan"]["status"] == "approved" and t["plan_current"] and len(t["runs"]) == 2 and t["signoff"] == signoff.TEST_SIGNOFF
    assert c.post(f"/api/projects/{pid}/testing/cycle").status_code == 409  # Dev's code isn't deployed in this test


def test_orion_checks_the_users_policy_changes(client):
    c, pid = _project("policy")
    prefix = "orkestra-acme-dev"
    aws_access.save(pid, {"status": "active", "prefix": prefix, "roles": [
        {"agent": "qa", "role": f"orkestra-{pid}-quinn", "policy": {"Version": "2012-10-17", "Statement": []}}]})
    ok, problems = aws_access.check_extra(pid, "qa", [
        {"Effect": "Allow", "Action": "sqs:PurgeQueue", "Resource": f"arn:aws:sqs:eu-west-1:144831534428:{prefix}*"},
        {"Effect": "Allow", "Action": ["sqs:GetQueueAttributes"], "Resource": "*"},
        {"Effect": "Deny", "Action": "lambda:InvokeFunction", "Resource": "*"}])
    assert not problems and ok[0]["Sid"] == "AddedByYou1" and ok[0]["Action"] == ["sqs:PurgeQueue"]
    _, problems = aws_access.check_extra(pid, "qa", [
        {"Effect": "Allow", "Action": "sqs:DeleteQueue", "Resource": "arn:aws:sqs:eu-west-1:144831534428:colleague-queue"},
        {"Effect": "Allow", "Action": "iam:CreateUser", "Resource": f"arn:aws:iam::144831534428:user/{prefix}x"},
        {"Effect": "Allow", "Action": "sqs:SendMessage", "Resource": "*"},
        {"Effect": "Allow", "NotAction": "s3:*", "Resource": "*"}])
    text = " ".join(problems)
    assert "colleague-queue isn't one of this project's resources" in text and "iam can't be added: identity and account-level" in text
    assert "only for read-only actions" in text and "NotAction isn't allowed" in text
    assert aws_access.check_extra(pid, "tp", [])[1]  # no role for Terra in this plan
    r = c.put(f"/api/projects/{pid}/access/cto/extra", json={"statements": [], "reason": "x"})
    assert r.status_code == 403  # Orion keeps the higher permission
    r = c.put(f"/api/projects/{pid}/access/qa/extra", json={"statements": [{"Effect": "Allow", "Action": "sqs:SendMessage", "Resource": "*"}]})
    assert r.status_code == 422 and r.json()["detail"]["problems"]
    r = c.put(f"/api/projects/{pid}/access/qa/extra", json={"statements": [{"Effect": "Deny", "Action": "sqs:DeleteMessage", "Resource": "*"}]})
    assert r.status_code == 200 and r.json()["policy"]["Statement"][-1]["Effect"] == "Deny"  # a check only: nothing applied


def test_the_demo_run_never_overwrites_real_work(client, captured):
    c, pid = _project("demoguard")

    async def go():  # a finished project, like msg-transformation when the demo overwrote its cards
        a = await flow.request_approval(pid, "live", "Quinn's test sign-off", "…", [])
        await flow.decide(pid, a.id, "approve", "")
    asyncio.run(go())
    r = c.post(f"/api/projects/{pid}/simulate")
    assert r.status_code == 409 and "real work" in r.json()["detail"]
    assert c.get("/api/system/health").json()["build"]  # the open tab compares it to offer a reload
